parameters:
#    ta_survey_security.example.class: TaSurvey\SecurityBundle\Example

services:
#    ta_survey_security.example:
#        class: %ta_survey_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
